Hotfix 1.4.x pdf metadata
gentics/mesh pull request #1157
Opened 2020-12-02 14:49 UTC by plyhun

## Abstract

The binary file with XML-based metadata (PDF) may be refused to upload into Mesh because of an array metadata field key. The provided fix allows such files for an upload. 

## Checklist

### General

* [x] Added abstract that describes the change
* [x] Added changelog entry to `/CHANGELOG.adoc`
* [x] Ensured that the change is covered by tests
* [x] Ensured that the change is documented in the docs

### On API Changes

* [x] Checked if the changes are breaking or not
* [x] Added GraphQL API if applicable
* [x] Added Elasticsearch mapping if applicable

2020-12-02 14:53 UTC, Jotschi requested changes

2020-12-02 14:53 UTC, Jotschi commented on core/src/main/java/com/gentics/mesh/core/data/node/field/impl/BinaryGraphFieldImpl.java
> +            String value = property(key);
```suggestion
            String value = property(name);
```

2020-12-02 14:53 UTC, Jotschi commented on core/src/main/java/com/gentics/mesh/core/data/node/field/impl/BinaryGraphFieldImpl.java
> +            name = key.replaceAll("%5D", "]");
```suggestion
            name = name.replaceAll("%5D", "]");
```

2020-12-02 17:59 UTC, Jotschi commented
Please also use the correct github email address in your commits. Otherwise the commits can't be tracked to your user. Use git ammend / rebase when you fixed the setting.

2020-12-03 10:22 UTC, plyhun commented
Done.

2020-12-17 11:32 UTC, closed without merging