Extend configuration for AWS S3 usage
gentics/mesh pull request #1183
Opened 2021-03-30 09:17 UTC by rhoxhaj

## Abstract

2021-03-31 09:06 UTC, yrucrem requested changes

2021-03-31 09:06 UTC, yrucrem commented on api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
> +	public S3Options getS3Options() {
Even though the `S3Options` do not have a validation method right now, I would still add them in the `MeshOptions` validate() method.

2021-03-31 09:06 UTC, yrucrem commented on api/src/main/java/com/gentics/mesh/etc/config/S3Options.java
> +        return this.s3cacheOptions;
Make sure this does not return `null`.

2021-04-01 09:43 UTC, yrucrem approved these changes

2021-04-01 10:30 UTC, plyhun approved these changes

2021-04-01 10:41 UTC, merged