CL-643: Generalize more DAO business logic by introducing low level database API in DAOs
gentics/mesh pull request #1246
Opened 2021-10-04 15:58 UTC by plyhun

## Abstract

In order to put more business logic off the DB-dependent impls into an API, we need to introduce some lower-level database API, for the raw persistent entity management. Otherwise the BL has to be copied around for every DB implementation.

## Checklist

### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

2021-11-02 15:21 UTC, npomaroli requested changes

2021-11-02 15:21 UTC, npomaroli commented on mdm/common/src/main/java/com/gentics/mesh/dagger/MeshBuilderFactory.java
> +package com.gentics.mesh.dagger;
This is a duplicate of MeshBuilderFactory in core, should this have been moved here?

2021-11-02 15:21 UTC, npomaroli commented on mdm/common/src/main/java/com/gentics/mesh/dagger/MeshComponent.java
> +package com.gentics.mesh.dagger;
This is a duplicate of MeshComponent in core, should this have been moved here?

2021-11-02 15:21 UTC, npomaroli commented on mdm/common/src/main/java/com/gentics/mesh/dagger/SearchProviderType.java
> +package com.gentics.mesh.dagger;
This is a duplicate of SearchProviderType in core.

2021-11-02 15:21 UTC, npomaroli commented on mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/AbstractContainerDaoWrapper.java
> +public abstract class AbstractContainerDaoWrapper<
Javadoc

2021-11-02 15:21 UTC, npomaroli commented on mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/AbstractCoreDaoWrapper.java
> +	public AbstractCoreDaoWrapper(Lazy<OrientDBBootstrapInitializer> boot, Lazy<PermissionPropertiesImpl> permissions) {
Javadoc

2021-11-02 15:21 UTC, npomaroli commented on mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/AbstractRootDaoWrapper.java
> +	public AbstractRootDaoWrapper(Lazy<OrientDBBootstrapInitializer> boot, Lazy<PermissionPropertiesImpl> permissions) {
Javadoc

2021-11-02 15:21 UTC, npomaroli commented on mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/db/AbstractTx.java
> +/**
This is a duplicate of AbstractTx in mesh-common

2021-11-03 11:31 UTC, merged

2021-11-03 16:39 UTC, plyhun commented on common/src/main/java/com/gentics/mesh/core/db/AbstractTx.java
> +	public <B extends HibBaseElement> void delete(B element, Class<? extends B> classOfB) {
-> https://github.com/gentics/mesh/pull/1262

2021-11-03 16:39 UTC, plyhun commented on common/src/main/java/com/gentics/mesh/core/db/AbstractTx.java
> +		return ((AbstractCoreDaoWrapper<?, ? extends B, ? extends B>) dao).persist(uuid);
-> https://github.com/gentics/mesh/pull/1262