Test fix leftovers
gentics/mesh pull request #1345
Opened 2022-03-21 11:06 UTC by plyhun

## Abstract

## Checklist

### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

2022-03-25 14:06 UTC, plyhun commented on tests/api/src/main/java/com/gentics/mesh/test/MeshOptionsProvider.java
> +			Class<? extends T> classToInstantiate = null;
This change allows more complex Provider class hierarchy.

2022-03-25 14:07 UTC, plyhun commented on tests/tests-core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerTest.java
> +		assertFalse(boot().isEmptyInstallation());
Neither of the commands below require an actual transaction.

2022-04-07 07:27 UTC, plyhun commented on tests/tests-core/src/main/java/com/gentics/mesh/core/field/node/NodeFieldEndpointTest.java
> +			NodeResponse response = updateNode(FIELD_NAME, new NodeFieldImpl().setUuid(newValue.getUuid()));
REST API calls should get removed from the transaction, because of a deadlock at some databases.

2022-04-07 08:43 UTC, npomaroli requested changes

2022-04-07 08:43 UTC, npomaroli commented on tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java
> +				System.out.println("Duration:" + i + " " + (duration / i));
Either use the logging system, or remove this output

2022-04-19 09:06 UTC, npomaroli commented on tests/tests-core/src/main/java/com/gentics/mesh/core/field/node/NodeFieldEndpointTest.java
> -		for (int i = 0; i < 20; i++) {
Why was this changed?

2022-04-19 13:08 UTC, plyhun commented on tests/tests-core/src/main/java/com/gentics/mesh/core/field/node/NodeFieldEndpointTest.java
> -		for (int i = 0; i < 20; i++) {
Mistakingly. Fixed!

2022-04-19 13:10 UTC, npomaroli approved these changes

2022-04-19 14:18 UTC, merged