Demo Refactored
gentics/mesh pull request #1397
Opened 2022-06-22 11:48 UTC by plyhun

## Abstract

## Checklist

### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

2022-06-23 11:32 UTC, plyhun commented on demo/common/src/main/java/com/gentics/mesh/demo/AbstractDemoDumper.java
> +public abstract class AbstractDemoDumper<T extends MeshOptions> extends AbstractMeshOptionsDemoContext<T> implements DemoDumper {
DemoDumpGenerator name remained unchanged for the default end-implementation, so Dumper name is given for an abstraction.

2022-06-23 11:36 UTC, plyhun commented on mdm/orientdb-api/src/main/java/com/gentics/mesh/etc/config/GraphStorageOptions.java
> +	public static final String DEFAULT_DATA_ROOT = "data";
Refactor

2022-06-24 08:46 UTC, udovidio requested changes

2022-06-27 09:31 UTC, plyhun commented on core/pom.xml
> +			</exclusions>
It is useless in general - no implementation needs this injected HikariCP (whatever the reason was to insert it there...).

2022-06-27 14:02 UTC, npomaroli approved these changes

2022-06-28 08:15 UTC, merged