Documentation changes for MDM
gentics/mesh pull request #1416
Opened 2022-07-11 12:56 UTC by plyhun

## Abstract

## Checklist

### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

2022-07-11 13:01 UTC, plyhun commented
WIP status: some markup troubles require attention of frontend dev.

2022-07-18 12:27 UTC, udovidio approved these changes

2022-07-19 07:05 UTC, npomaroli requested changes

2022-07-19 07:05 UTC, npomaroli commented on distributed-coordinator/README.md
> +This module contains the clustering code for the coordination feature / request delegation and needed master election. OrientDB-specific implementation.
The coordination feature, especially the master election is not OrientDB specific.
The elected master will also be the instance, which runs background jobs (like schema migration) and handles elasticsearch sync

2022-07-19 07:05 UTC, npomaroli commented on distributed/README.md
> +This module contains code which is needed for cluster support. OrientDB-specific implementation.
Not OrientDB specific

2022-07-20 07:43 UTC, merged