WIP: Openapi
gentics/mesh pull request #1417
Opened 2022-07-11 15:41 UTC by plyhun

## Abstract

Serve OpenAPI YAMS / JSON schema requests.

## Checklist

### General

* [x] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [x] Ensured that the change is covered by tests
* [x] Ensured that the change is documented in the docs

### On API Changes

* [x] Checked if the changes are breaking or not
* [x] Added GraphQL API if applicable
* [x] Added Elasticsearch mapping if applicable

2022-07-20 09:32 UTC, npomaroli requested changes

2022-07-20 09:32 UTC, npomaroli commented on core/src/main/java/com/gentics/mesh/generator/OpenAPIv3Generator.java
> +				System.out.println(fullPath);
Is this debug output? If yes, please remove.

2022-07-20 09:32 UTC, npomaroli commented on core/src/main/java/com/gentics/mesh/generator/OpenAPIv3Generator.java
> +				System.err.println(t + " / " + Arrays.toString(generics.toArray()));
Debug output?

2022-07-20 09:32 UTC, npomaroli commented on core/src/main/java/com/gentics/mesh/generator/OpenAPIv3Generator.java
> +			System.err.println(Arrays.toString(generics.toArray()));
Debug output?

2022-07-20 09:32 UTC, npomaroli commented on core/src/main/java/com/gentics/mesh/core/endpoint/admin/RestInfoEndpoint.java
> +		secure("/openapi.yaml");
Please add a changelog for the new endpoints

2022-07-20 10:44 UTC, plyhun commented
Tests missing here.

2024-06-11 11:10 UTC, plyhun commented on core/src/main/java/com/gentics/mesh/core/endpoint/RolePermissionHandlingEndpoint.java
> +
HTTP standard has no directions over DELETE methods with body, so the client generator fails on the method above, as not following the standard.

2026-03-03 16:31 UTC, closed without merging