Image manipulation refactoring
gentics/mesh pull request #1524
Opened 2023-08-01 10:24 UTC by plyhun

## Abstract

Image manipulation has been refactored for performance. This contains:

* Option for turning off
* Option for storing the manipulated image variant permanently
* REST API for managing the image variants 

## Checklist

### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

2023-08-01 10:25 UTC, plyhun commented on mdm/common/src/main/java/com/gentics/mesh/context/impl/InternalRoutingActionContextImpl.java
> +		return rc.body().asString();
Undeprecate stuff.

2023-08-08 13:43 UTC, plyhun commented on core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryDownloadHandler.java
> +import com.gentics.mesh.core.data.HibAntivirableBinaryElement;
The antivirus-checkable binary entity has been split away from the ordinary binary data definition - image variants are not necessary to check.

2023-08-08 14:02 UTC, plyhun commented on rest-model/src/main/java/com/gentics/mesh/core/rest/node/NodePublishRequest.java
> +public class NodePublishRequest extends ImageManipulationRequest {
Perhaps a composition is better here than inheritance.

2023-08-11 08:46 UTC, npomaroli commented on mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBinaryDao.java
> +	void deletePersistingVariant(HibBinary binary, HibImageVariant variant);
maybe rename to deletePersistedVariant

2023-08-11 08:46 UTC, npomaroli commented on mdm/api/src/main/java/com/gentics/mesh/core/data/dao/BinaryDao.java
> +	Result<? extends HibImageVariant> deleteVariants(HibBinary binary, Collection<ImageVariantRequest> variant, InternalActionContext ac, boolean deleteOther);
Maybe it's clearer to make two methods out of this:
deleteVariants() which deletes the given variants
retainVariants() which deletes all but the the given variants

2023-09-22 14:45 UTC, plyhun commented on changelog/src/changelog/entries/2023/09/7560.GPU-1115.enhancement
> +Core: The on-demand image manipulation feature has been refactored for DDoS protection. The new image manipulator option, `mode`, has been added with the following values:
Perhaps I'd need some less targeted description...

2023-09-22 15:04 UTC, plyhun commented on core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
> +		//webrootFieldHandler.handlePostPathField(ac);
This will require a separate story, as there is just too much to handle.

2023-09-22 15:13 UTC, plyhun commented on mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingS3BinaryDao.java
> +public interface PersistingS3BinaryDao extends S3BinaryDao {
Forgotten by everyone :(

2023-09-28 10:08 UTC, npomaroli requested changes

2024-03-13 13:10 UTC, merged