GPU-994 - Java 17 Update
gentics/mesh pull request #1558
Opened 2023-11-21 12:26 UTC by guggi

## Abstract

## Checklist

### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

2023-11-21 12:27 UTC, guggi commented on .jenkins/Dockerfile
> +# Install Java 11
are old versions still needed or are we safe to remove alternative java version?

2023-11-27 08:16 UTC, guggi commented on tests/pom.xml
> +					<argLine>--add-opens=java.base/java.lang=ALL-UNNAMED ${jacoco.env}</argLine>
todo: check if needed

2024-01-15 14:02 UTC, npomaroli requested changes

2024-01-16 09:51 UTC, guggi commented on tests/pom.xml
> +			<plugin>
[c98f0a7](https://github.com/gentics/mesh/pull/1558/commits/c98f0a7a9c92ab494da9285cb9c540646e3fe936)

2024-01-16 09:51 UTC, guggi commented on pom.xml
> +				<version>3.11.0</version>
[c98f0a7](https://github.com/gentics/mesh/pull/1558/commits/c98f0a7a9c92ab494da9285cb9c540646e3fe936)

2024-01-16 09:53 UTC, merged